modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"


[[mods]]
modId="recdec"
version="0.1.0"
displayName="Bixel Decoration Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Mcjty, TurtyWurty"
authors="Bixel"

description='''
This mod adds inspired new decorative blocks I saw in the Minecraft Dungeons
'''

[[dependencies.rec]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    # versionRange="[32,)" 1.16.1
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"

